### ISSUE TITLE
Please do NOT release breaking changes without major version increase

### ISSUE THREAD

**Issue by flexchar** [nitotm/efficient-language-detector#5]
Hi Nito,

it's an amazing package you've done that I decided to put into a system running in production. I regularly `composer update` with allowing minor or patch updates. Unfortunately this broke the functionality. 

Please do NOT release breaking changes without major version increase. Commit with a breaking change: 4ec850bf20b307ea519f6ccad79426f2a6c06db5

Method example before:
```php
$lang = $this->ld->detect(
            text: $text,
            cleanText: true,
            checkConfidence: false,
            minByteLength: 1,
            minNgrams: strlen($text) > 30 ? 5 : 2,
        );
```

After, which is current:
```php
$lang = $this->ld->detect(
            text: $text,
        );
```

Please don't. Hope this message finds you well. 

PS. I also believe it may have been a mistake because now it is not possible to toggle `cleanText` function. I'd kindly suggest you to drop support to below PHP 8.1 and put `public bool $cleanText = false;` inside the constructor thus utilizing [PHP Promoted properties](https://stitcher.io/blog/constructor-promotion-in-php-8).

**Comment by nitotm** [comment]
Sorry, I was unsure if from v1.0.3  to v1.1.0 was enough, I guess the correct version would have been v2.0.0?

Regarding `cleanText`, I'm not sure what is the problem you are having. 
```php
$eld->cleanText = true;
$result = $eld->detect($text); // $text will be cleaned, here and on subsequent calls
$eld->cleanText = false; // Default
$result = $eld->detect($text); // Text will not be cleaned, ... 
```
I thought it’s better to set it once, in case you want to clean the text, instead of at every `detect()`.
It wasn’t an option before to set it on the constructor either.

Also, without changing the source code you can make sure it’s clear on the same line that the text is being clean by doing:
`$eld->detect( $eld->getCleanText($text) ); `
Probably not the proper way you want to use a class, like `$foo->getCleanText($text)->detect()`, but again the official way I choose to do it is with `$eld->cleanText = bool`.

Anything else, let me know, because probably I haven’t understood correctly the `cleanText` problem.

**Comment by flexchar** [comment]
For the versioning, yes, you're correct. It should be 2.0.0. Major.minor.patch. You may kindly check out https://semver.org/ on this one. :) 

Sorry for the mistake with `cleanText`, you're right - it is indeed possible to toggle it directly. However the best practice is to do so using `->cleanText(bool $bool = true): self` method on the class instead of directly modifying the property. It'd be a great practice if you could add dedicated method.

**Comment by flexchar** [comment]
Thank you, Nito. I appreciate the prompt response.
